export enum ConfigurationKeyEnum {
  DEFAULT_SMS_SERVICE = 'DEFAULT_SMS_SERVICE',
  DEFAULT_PUSHER_SERVICE = 'DEFAULT_PUSHER_SERVICE',
  QUEUE_DELAY_IN_SEC = 'QUEUE_DELAY_IN_SEC',
  LIMIT_OF_SENT_NOTIFICATIONS_IN_MINUTE = 'LIMIT_OF_SENT_NOTIFICATIONS_IN_MINUTE'
}

export enum NotificationProvidersEnum {
  AWS_SNS_SMS = 'AWS_SNS_SMS',
  TWILIO_SMS = 'TWILIO_SMS',
  FIREBASE_PUSHER = 'FIREBASE_PUSHER',
  ONE_SIGNAL_PUSHER = 'ONE_SIGNAL_PUSHER'
}
