export enum ConfigurationKeyEnum {
  DEFAULT_SMS_SERVICE = 'DEFAULT_SMS_SERVICE',
  DEFAULT_PUSHER_SERVICE = 'DEFAULT_PUSHER_SERVICE'
}

export enum ConfigurationValueEnum {
  AWS_SNS = 'AWS_SNS_SMS',
  TWILIO_SMS = 'TWILIO_SMS',
  FIREBASE_PUSHER = 'FIREBASE_PUSHER',
  ONE_SIGNAL_PUSHER = 'ONE_SIGNAL_PUSHER'
}
